// <auto-generated />
using System;
using MaturaGenerator.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MaturaGenerator.Migrations
{
    [DbContext(typeof(MaturaDbContext))]
    [Migration("20260929145934_AddProblemTemplateSchema")]
    partial class AddProblemTemplateSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MaturaGenerator.Models.DomainConstraint", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ConstantNames")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("nvarchar(21)");

                    b.Property<int>("ProblemTemplateId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProblemTemplateId");

                    b.ToTable("DomainConstraints");

                    b.HasDiscriminator<string>("Discriminator").HasValue("DomainConstraint");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("MaturaGenerator.Models.ProblemTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Structure")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("TargetGrade")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.ToTable("ProblemTemplates");
                });

            modelBuilder.Entity("MaturaGenerator.Models.TemplateRule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Expression")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("ProblemTemplateId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProblemTemplateId");

                    b.ToTable("TemplateRules");
                });

            modelBuilder.Entity("MaturaGenerator.Models.DomainConstraints.FractionDomain", b =>
                {
                    b.HasBaseType("MaturaGenerator.Models.DomainConstraint");

                    b.Property<int>("MaxDenominator")
                        .HasColumnType("int");

                    b.Property<int>("MaxNumerator")
                        .HasColumnType("int");

                    b.Property<int>("MinDenominator")
                        .HasColumnType("int");

                    b.Property<int>("MinNumerator")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue("FractionDomain");
                });

            modelBuilder.Entity("MaturaGenerator.Models.DomainConstraints.IntDomain", b =>
                {
                    b.HasBaseType("MaturaGenerator.Models.DomainConstraint");

                    b.Property<int>("MaxValue")
                        .HasColumnType("int");

                    b.Property<int>("MinValue")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue("IntDomain");
                });

            modelBuilder.Entity("MaturaGenerator.Models.DomainConstraint", b =>
                {
                    b.HasOne("MaturaGenerator.Models.ProblemTemplate", "ProblemTemplate")
                        .WithMany("Domains")
                        .HasForeignKey("ProblemTemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProblemTemplate");
                });

            modelBuilder.Entity("MaturaGenerator.Models.TemplateRule", b =>
                {
                    b.HasOne("MaturaGenerator.Models.ProblemTemplate", "ProblemTemplate")
                        .WithMany("Rules")
                        .HasForeignKey("ProblemTemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProblemTemplate");
                });

            modelBuilder.Entity("MaturaGenerator.Models.ProblemTemplate", b =>
                {
                    b.Navigation("Domains");

                    b.Navigation("Rules");
                });
#pragma warning restore 612, 618
        }
    }
}
